version: "3.3"
services:
  dlg-forks-server:
    image: dgl-forks:latest
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:2222:22"
    volumes:
      - versionsdb:/versionsdb/
      - crawl-master:/crawl-master/
      - dgldir:/dgldir/
      - usr-games:/usr/games
volumes:
  versionsdb:
    external: true
  crawl-master:
    external: true
  dgldir:
    external: true
  usr-games:
    external: true