services:
  dcss-server:
    image: refracta/dcss-server:latest
    tty: true
    stdin_open: true
    build:
      context: ../
      dockerfile: server/Dockerfile
    ports:
      - "0:22"
      - "0:8022"
      - "0:8080"
      - "0:8081"
      - "0:8082"
    volumes:
      - ./data/config:/home/crawl-dev/dgamelaunch-config
      - ./data/versionsdb:/versionsdb
      - ./data/crawl-master:/crawl-master
      - ./data/dgldir:/dgldir
      - ./data/games:/usr/games
      - ./data/ccache:/root/.cache/ccache
      - ./data/ssh-keys:/etc/ssh/keys
      - ./data/:/data
    environment:
      - CMD
      - USE_REVERSE_PROXY
      - USE_DWEM
      - USE_CNC_CONFIG
      - GH_TOKEN
