services:
  dcss-server:
    image: refracta/dcss-server:latest
    tty: true
    stdin_open: true
    build:
      context: ../
      dockerfile: server/Dockerfile
    ports:
      - "0:8080"
      - "0:8081"
      - "0:8082"
      - "0:22"
    volumes:
      - ./data/config:/home/crawl-dev/dgamelaunch-config
      - ./data/versionsdb:/home/crawl/DGL/versionsdb
      - ./data/crawl-master:/home/crawl/DGL/crawl-master
      - ./data/dgldir:/home/crawl/DGL/dgldir
      - ./data/games:/home/crawl/DGL/usr/games
      - ./data/ccache:/root/.cache/ccache
      - ./data/:/data
    environment:
      - CMD
      - USE_REVERSE_PROXY
      - USE_DWEM
      - USE_CNC_CONFIG
      - GH_TOKEN
