name: build-all

on:
  push:
    branches: [ master, test-* ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
    - uses: actions/checkout@v2

    - name: Docker container build
      run: |
        utils/build-testing-container.sh

    - name: Docker container test
      run: |
        cd utils/testing-container
        sed -i 's|entrypoint:.*|entrypoint: /docker-entrypoint-build-all.sh|' docker-compose.yaml
        docker-compose up