name: build-all

on:
  push:
    branches: [ master, test-* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker container test
      run: |
        cd server
        cp docker-compose.build-all.yml docker-compose.override.yml
        docker-compose up
